CREATE TABLE USER(
	Username VARCHAR(255) NOT NULL,
	Password VARCHAR(255),
	PRIMARY KEY(Username)
);

CREATE TABLE RECIPE(
	Title VARCHAR(511) NOT NULL,
	Instruction TEXT(2047),
	Time INT,
	Difficulty INT,
	Total_cost INT,
	Picture_url VARCHAR(1023), 
	Rating FLOAT,
	USER_Username VARCHAR(255) NOT NULL,
	PRIMARY KEY(Title),
	FOREIGN KEY(USER_Username) REFERENCES USER(Username)
);

CREATE TABLE REVIEW(
	Id INT NOT NULL AUTO_INCREMENT,
	Content TEXT(2047),
	Rating INT,
	USER_Username VARCHAR(255) NOT NULL,
	RECI_Title VARCHAR(511) NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(USER_Username) REFERENCES USER(Username),
	FOREIGN KEY(RECI_Title) REFERENCES RECIPE(Title) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INGREDIENT(
	Name VARCHAR(15) NOT NULL,
	Cost INT,
	PRIMARY KEY(Name)
);

CREATE TABLE USES(
	INGR_Name VARCHAR(15) NOT NULL,
	RECI_Title VARCHAR(511) NOT NULL,
	Ingredient_quantity INT,
	PRIMARY KEY(INGR_Name, RECI_Title),
	FOREIGN KEY(INGR_Name) REFERENCES INGREDIENT(Name),
	FOREIGN KEY(RECI_Title) REFERENCES RECIPE(Title) ON DELETE CASCADE ON UPDATE CASCADE
);
